# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 13:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_tag',
            field=models.CharField(default='kek', max_length=100),
            preserve_default=False,
        ),
    ]
