# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-16 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_post_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_tag',
            field=models.SlugField(max_length=100),
        ),
    ]
