# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 08:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160216_1413'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_text', models.CharField(max_length=50)),
                ('tag_slug', models.SlugField()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_tag',
        ),
    ]
