# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_add_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='tag_slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
