# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 21:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20160218_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='http://shere.buruma.net/wp-content/uploads/2014/09/django.png', upload_to=''),
        ),
    ]
