# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-23 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20160223_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_slug',
            field=models.SlugField(editable=False, max_length=200),
        ),
    ]
